name: API Kin Automation

on:
 workflow_dispatch:
    inputs:
      amb:
        description: 'Select environment: staging / production'
        required: false
        default: 'production'

permissions:
  contents: write

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']
    steps:
    - uses: actions/checkout@v3
    - name: API Kin Automation
      uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      # load env varibles from secrets
      env:
        KIN_API_KEY: ${{ secrets.PASSWORD }}
        KIN_API_SECRET: ${{ secrets.USERNAME }}
      run: bundle exec rspec -f j -o tmp/rspec_results.json -f p
    - name: Upload results - Report
      uses: SonicGarden/rspec-report-action@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json-path: tmp/rspec_results.json
      if: always()