name: API Kin Automation

on:
 workflow_dispatch:
    inputs:
      amb:
        description: 'Select environment: staging / production'
        required: false
        default: 'production'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-ruby@v3
      with:
          ruby-version: 2.7
          bundler-cache: true
    - name: Install rspec
      run: gem install rspec
    - name: Run bundle install
      run:  gem install bundler | bundle install --jobs 4 --retry 3
    - name: Run tests
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
        USERNAME: ${{ secrets.USERNAME }}
      run: bundle exec rspec -f j -o tmp/rspec_results.json -f p
    - name: Upload results - Report
      uses: SonicGarden/rspec-report-action@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json-path: tmp/rspec_results.json
      if: always()